export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const MSG_SUCCESS = 'MSG_SUCCESS';
export const MSG_ERROR = 'MSG_ERROR';
export const MSG_REMOVE = 'MSG_REMOVE';

export const GET_POSITIONS = 'GET_POSITIONS';
export const GET_DUTIES = 'GET_DUTIES';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_PAYROLLS = 'GET_PAYROLLS';
export const GET_PAYROLLS_EMPLOYEES = 'GET_PAYROLLS_EMPLOYEES';

export const GET_ALL_PAYROLLS = 'GET__ALL_PAYROLLS';
